"""empty message

Revision ID: ab81df3436eb
Revises: 7060b5e806bf
Create Date: 2018-06-21 17:25:03.283412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab81df3436eb'
down_revision = '7060b5e806bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('expiration_date', table_name='shop')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('expiration_date', 'shop', ['expiration_date'], unique=True)
    # ### end Alembic commands ###
